name: card_organizer
description: A Flutter app to organize playing cards in folders. 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  http: ^0.13.3
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
